name: CD Deploy

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed


jobs:

  deploy:

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: self-hosted


    steps:

      - name: Login to Docker Hub
        run: |
          docker login \
          -u ${{ secrets.DOCKER_USERNAME }} \
          -p ${{ secrets.DOCKER_PASSWORD }}


      - name: Pull latest image
        run: |
          docker pull \
          ${{ secrets.DOCKER_USERNAME }}/spring-auth:latest


      - name: Remove old container
        shell: powershell
        run: |
          $container = docker ps -aq -f "name=spring-auth"

          if ($container) {
              docker stop spring-auth
              docker rm spring-auth
          }


      - name: Run new container
        run: |
          docker run -d `
          --name spring-auth `
          -p 8080:8080 `
          ${{ secrets.DOCKER_USERNAME }}/spring-auth:latest